# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLThreatsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threat',
            old_name='urllink',
            new_name='description',
        ),
        migrations.AddField(
            model_name='threat',
            name='reverse_lookup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
